// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockDemo.API.Data;

#nullable disable

namespace StockDemo.API.Migrations
{
    [DbContext(typeof(StockDemoDbContext))]
    [Migration("20260713135015_AddDeviceTokens")]
    partial class AddDeviceTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockDemo.API.Models.Domain.DeliveryOrder", b =>
                {
                    b.Property<int>("DeliveryOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryOrderId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PONumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DeliveryOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("DeliveryOrders");

                    b.HasData(
                        new
                        {
                            DeliveryOrderId = 1,
                            CreatedDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeliveryDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PONumber = "PO-2024-001",
                            ProductId = 1,
                            QRCode = "PRD001;2024-01-15;PO-2024-001",
                            Quantity = 50,
                            Status = "Delivered"
                        },
                        new
                        {
                            DeliveryOrderId = 2,
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeliveryDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PONumber = "PO-2024-002",
                            ProductId = 2,
                            QRCode = "PRD002;2024-01-20;PO-2024-002",
                            Quantity = 200,
                            Status = "Delivered"
                        },
                        new
                        {
                            DeliveryOrderId = 3,
                            CreatedDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeliveryDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PONumber = "PO-2024-003",
                            ProductId = 3,
                            QRCode = "PRD003;2024-02-01;PO-2024-003",
                            Quantity = 100,
                            Status = "InTransit"
                        });
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.DeviceToken", b =>
                {
                    b.Property<int>("DeviceTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceTokenId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<string>("Platform")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DeviceTokenId");

                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.EpcMapping", b =>
                {
                    b.Property<string>("Epc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("MappedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Epc");

                    b.HasIndex("StockId");

                    b.ToTable("EpcMappings");

                    b.HasData(
                        new
                        {
                            Epc = "A00000000000000000000250",
                            MappedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 1
                        },
                        new
                        {
                            Epc = "A00000000000000000000251",
                            MappedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 3
                        },
                        new
                        {
                            Epc = "A00000000000000000000252",
                            MappedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 2
                        },
                        new
                        {
                            Epc = "A00000000000000000000253",
                            MappedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 4
                        },
                        new
                        {
                            Epc = "A00000000000000000000264",
                            MappedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 1
                        },
                        new
                        {
                            Epc = "A00000000000000000000265",
                            MappedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 2
                        },
                        new
                        {
                            Epc = "A00000000000000000000266",
                            MappedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 4
                        },
                        new
                        {
                            Epc = "A00000000000000000000267",
                            MappedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 3
                        });
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LocationCode = "A-01",
                            LocationName = "Khu A - Tầng 1"
                        },
                        new
                        {
                            LocationId = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LocationCode = "A-02",
                            LocationName = "Khu A - Tầng 2"
                        },
                        new
                        {
                            LocationId = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LocationCode = "B-01",
                            LocationName = "Khu B - Tầng 1"
                        },
                        new
                        {
                            LocationId = 4,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LocationCode = "C-01",
                            LocationName = "Khu C - Tầng 1"
                        });
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxQuantity")
                        .HasColumnType("int");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Laptop văn phòng, màn hình 15.6 inch",
                            IsActive = true,
                            MaxQuantity = 100,
                            MinQuantity = 45,
                            ProductCode = "PRD001",
                            ProductName = "Laptop Dell Inspiron 15",
                            Unit = "Cái"
                        },
                        new
                        {
                            ProductId = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chuột không dây, pin 24 tháng",
                            IsActive = true,
                            MinQuantity = 50,
                            ProductCode = "PRD002",
                            ProductName = "Chuột Logitech M331",
                            Unit = "Cái"
                        },
                        new
                        {
                            ProductId = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bàn phím cơ RGB, switch blue",
                            IsActive = true,
                            MinQuantity = 20,
                            ProductCode = "PRD003",
                            ProductName = "Bàn phím Mechanical K552",
                            Unit = "Cái"
                        },
                        new
                        {
                            ProductId = 4,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Màn hình Full HD, IPS",
                            IsActive = true,
                            MinQuantity = 40,
                            ProductCode = "PRD004",
                            ProductName = "Màn hình LG 24 inch",
                            Unit = "Cái"
                        },
                        new
                        {
                            ProductId = 5,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "USB 3.0, tốc độ cao",
                            IsActive = true,
                            MinQuantity = 500,
                            ProductCode = "PRD005",
                            ProductName = "USB Kingston 32GB",
                            Unit = "Cái"
                        });
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.Stock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockId"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("StockId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            StockId = 1,
                            LastUpdated = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            ProductId = 1,
                            QRCode = "PRD001;2024-01-15;PO-2024-001",
                            Quantity = 40
                        },
                        new
                        {
                            StockId = 2,
                            LastUpdated = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 2,
                            ProductId = 2,
                            QRCode = "PRD002;2024-01-20;PO-2024-002",
                            Quantity = 150
                        },
                        new
                        {
                            StockId = 3,
                            LastUpdated = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3,
                            ProductId = 4,
                            QRCode = "PRD004;2024-01-25;PO-2024-004",
                            Quantity = 30
                        },
                        new
                        {
                            StockId = 4,
                            LastUpdated = new DateTime(2024, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 4,
                            ProductId = 5,
                            QRCode = "PRD005;2024-01-28;PO-2024-005",
                            Quantity = 400
                        });
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.StockIn", b =>
                {
                    b.Property<int>("StockInId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockInId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("StockInId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.ToTable("StockIn");

                    b.HasData(
                        new
                        {
                            StockInId = 1,
                            CreatedBy = 2,
                            CreatedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            ProductId = 1,
                            QRCode = "PRD001;2024-01-15;PO-2024-001",
                            Quantity = 50
                        },
                        new
                        {
                            StockInId = 2,
                            CreatedBy = 3,
                            CreatedDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 2,
                            ProductId = 2,
                            QRCode = "PRD002;2024-01-20;PO-2024-002",
                            Quantity = 200
                        },
                        new
                        {
                            StockInId = 3,
                            CreatedBy = 2,
                            CreatedDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 3,
                            ProductId = 4,
                            QRCode = "PRD004;2024-01-25;PO-2024-004",
                            Quantity = 30
                        },
                        new
                        {
                            StockInId = 4,
                            CreatedBy = 3,
                            CreatedDate = new DateTime(2024, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 4,
                            ProductId = 5,
                            QRCode = "PRD005;2024-01-28;PO-2024-005",
                            Quantity = 500
                        });
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.StockOut", b =>
                {
                    b.Property<int>("StockOutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockOutId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("StockOutId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.ToTable("StockOut");

                    b.HasData(
                        new
                        {
                            StockOutId = 1,
                            CreatedBy = 3,
                            CreatedDate = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            ProductId = 1,
                            QRCode = "PRD001;2024-01-15;PO-2024-001",
                            Quantity = 10
                        },
                        new
                        {
                            StockOutId = 2,
                            CreatedBy = 3,
                            CreatedDate = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 2,
                            ProductId = 2,
                            QRCode = "PRD002;2024-01-20;PO-2024-002",
                            Quantity = 50
                        },
                        new
                        {
                            StockOutId = 3,
                            CreatedBy = 2,
                            CreatedDate = new DateTime(2024, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 4,
                            ProductId = 5,
                            QRCode = "PRD005;2024-01-28;PO-2024-005",
                            Quantity = 100
                        });
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.StockTake", b =>
                {
                    b.Property<int>("StockTakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockTakeId"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StockTakeId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LocationId");

                    b.ToTable("StockTakes");
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.StockTakeItem", b =>
                {
                    b.Property<int>("StockTakeItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockTakeItemId"));

                    b.Property<int>("CountedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("StockTakeId")
                        .HasColumnType("int");

                    b.Property<int>("SystemQuantity")
                        .HasColumnType("int");

                    b.Property<int>("Variance")
                        .HasColumnType("int");

                    b.HasKey("StockTakeItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockTakeId");

                    b.ToTable("StockTakeItems");
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.StockTransfer", b =>
                {
                    b.Property<int>("StockTransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockTransferId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromLocationId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ToLocationId")
                        .HasColumnType("int");

                    b.HasKey("StockTransferId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ToLocationId");

                    b.ToTable("StockTransfers");
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Administrator",
                            IsActive = true,
                            PasswordHash = "vKjULaJ033cQ76FN/YbnpW0cLjFZWmecQtQGjO5QgQZt8Pxoj8J3JTjEALz4NDnA",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nguyen Van A",
                            IsActive = true,
                            PasswordHash = "vKjULaJ033cQ76FN/YbnpW0cLjFZWmecQtQGjO5QgQZt8Pxoj8J3JTjEALz4NDnA",
                            Role = "Manager",
                            Username = "manager1"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Tran Thi B",
                            IsActive = true,
                            PasswordHash = "vKjULaJ033cQ76FN/YbnpW0cLjFZWmecQtQGjO5QgQZt8Pxoj8J3JTjEALz4NDnA",
                            Role = "Staff",
                            Username = "staff1"
                        });
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.DeliveryOrder", b =>
                {
                    b.HasOne("StockDemo.API.Models.Domain.Product", "Product")
                        .WithMany("DeliveryOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.EpcMapping", b =>
                {
                    b.HasOne("StockDemo.API.Models.Domain.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.Stock", b =>
                {
                    b.HasOne("StockDemo.API.Models.Domain.Location", "Location")
                        .WithMany("Stocks")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockDemo.API.Models.Domain.Product", "Product")
                        .WithMany("Stocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.StockIn", b =>
                {
                    b.HasOne("StockDemo.API.Models.Domain.User", "User")
                        .WithMany("StockIns")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockDemo.API.Models.Domain.Location", "Location")
                        .WithMany("StockIns")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockDemo.API.Models.Domain.Product", "Product")
                        .WithMany("StockIns")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.StockOut", b =>
                {
                    b.HasOne("StockDemo.API.Models.Domain.User", "User")
                        .WithMany("StockOuts")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockDemo.API.Models.Domain.Location", "Location")
                        .WithMany("StockOuts")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockDemo.API.Models.Domain.Product", "Product")
                        .WithMany("StockOuts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.StockTake", b =>
                {
                    b.HasOne("StockDemo.API.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockDemo.API.Models.Domain.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.StockTakeItem", b =>
                {
                    b.HasOne("StockDemo.API.Models.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockDemo.API.Models.Domain.StockTake", "StockTake")
                        .WithMany("Items")
                        .HasForeignKey("StockTakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StockTake");
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.StockTransfer", b =>
                {
                    b.HasOne("StockDemo.API.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockDemo.API.Models.Domain.Location", "FromLocation")
                        .WithMany()
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockDemo.API.Models.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockDemo.API.Models.Domain.Location", "ToLocation")
                        .WithMany()
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromLocation");

                    b.Navigation("Product");

                    b.Navigation("ToLocation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.Location", b =>
                {
                    b.Navigation("StockIns");

                    b.Navigation("StockOuts");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.Product", b =>
                {
                    b.Navigation("DeliveryOrders");

                    b.Navigation("StockIns");

                    b.Navigation("StockOuts");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.StockTake", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("StockDemo.API.Models.Domain.User", b =>
                {
                    b.Navigation("StockIns");

                    b.Navigation("StockOuts");
                });
#pragma warning restore 612, 618
        }
    }
}
